// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnst6V6G0-RylvMmMd-JoD1elG8vlHGI',
    appId: '1:223216256838:web:15539a54d0858240e20747',
    messagingSenderId: '223216256838',
    projectId: 'eu-mart-mobile',
    authDomain: 'eu-mart-mobile.firebaseapp.com',
    storageBucket: 'eu-mart-mobile.firebasestorage.app',
    measurementId: 'G-56WF6TB6CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKL29QcdnXrloJqAhocIKYoHmWUxMCX7E',
    appId: '1:223216256838:android:a9ce4342b78dd437e20747',
    messagingSenderId: '223216256838',
    projectId: 'eu-mart-mobile',
    storageBucket: 'eu-mart-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACXDXHuAwhGjvllCc-t3oVNTotKVm5FhY',
    appId: '1:223216256838:ios:b495b88ff401404ae20747',
    messagingSenderId: '223216256838',
    projectId: 'eu-mart-mobile',
    storageBucket: 'eu-mart-mobile.firebasestorage.app',
    iosClientId: '223216256838-g7k0jcsvphjkbame5j5ot0dq6tgsue0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.euMartFeedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACXDXHuAwhGjvllCc-t3oVNTotKVm5FhY',
    appId: '1:223216256838:ios:b495b88ff401404ae20747',
    messagingSenderId: '223216256838',
    projectId: 'eu-mart-mobile',
    storageBucket: 'eu-mart-mobile.firebasestorage.app',
    iosClientId: '223216256838-g7k0jcsvphjkbame5j5ot0dq6tgsue0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.euMartFeedback',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPnst6V6G0-RylvMmMd-JoD1elG8vlHGI',
    appId: '1:223216256838:web:d07d6274a31e547ee20747',
    messagingSenderId: '223216256838',
    projectId: 'eu-mart-mobile',
    authDomain: 'eu-mart-mobile.firebaseapp.com',
    storageBucket: 'eu-mart-mobile.firebasestorage.app',
    measurementId: 'G-CC8SWW1LYR',
  );
}
