class CartItem {
  final String id;
  final String productName;
  final String imagePath;

  /// Original selling price saved in Firestore.
  final double originalPrice;

  /// Available product stock at the time it was added to the cart.
  final int availableStock;

  final bool promoActive;
  final String promoType;
  final String promoLabel;
  final double discountPercent;
  final int buyQuantity;
  final int freeQuantity;

  /// Paid quantity selected by the cashier.
  int quantity;

  CartItem({
    required this.id,
    required this.productName,
    required this.originalPrice,
    required this.availableStock,
    this.imagePath = '',
    this.promoActive = false,
    this.promoType = '',
    this.promoLabel = '',
    this.discountPercent = 0,
    this.buyQuantity = 1,
    this.freeQuantity = 0,
    this.quantity = 1,
  });

  /// Discounted selling price for percentage-based promos.
  double get effectiveUnitPrice {
    if (!promoActive || promoType != 'percentage') {
      return originalPrice;
    }

    final safeDiscount = discountPercent.clamp(0, 100);
    return originalPrice * (1 - safeDiscount / 100);
  }

  /// Number of free units generated by Buy 1 Take 1 or similar promos.
  int get promoFreeUnits {
    if (!promoActive ||
        promoType != 'buy1take1' ||
        buyQuantity <= 0 ||
        freeQuantity <= 0) {
      return 0;
    }

    return (quantity ~/ buyQuantity) * freeQuantity;
  }

  /// Total physical quantity that will be removed from inventory.
  int get totalStockQuantity => quantity + promoFreeUnits;

  /// Amount paid by the customer.
  double get subtotal => effectiveUnitPrice * quantity;

  /// Checks whether another paid unit may be added without exceeding stock.
  bool get canIncrease {
    final nextPaidQuantity = quantity + 1;

    int nextFreeUnits = 0;

    if (promoActive &&
        promoType == 'buy1take1' &&
        buyQuantity > 0 &&
        freeQuantity > 0) {
      nextFreeUnits = (nextPaidQuantity ~/ buyQuantity) * freeQuantity;
    }

    return nextPaidQuantity + nextFreeUnits <= availableStock;
  }

  /// Useful when saving item details to Firestore.
  Map<String, dynamic> toMap() {
    return {
      'productId': id,
      'productName': productName,
      'imagePath': imagePath,
      'originalPrice': originalPrice,
      'unitPrice': effectiveUnitPrice,
      'quantity': quantity,
      'freeQuantity': promoFreeUnits,
      'totalStockQuantity': totalStockQuantity,
      'subtotal': subtotal,
      'promoActive': promoActive,
      'promoType': promoType,
      'promoLabel': promoLabel,
      'discountPercent': discountPercent,
    };
  }

  CartItem copyWith({
    String? id,
    String? productName,
    String? imagePath,
    double? originalPrice,
    int? availableStock,
    bool? promoActive,
    String? promoType,
    String? promoLabel,
    double? discountPercent,
    int? buyQuantity,
    int? freeQuantity,
    int? quantity,
  }) {
    return CartItem(
      id: id ?? this.id,
      productName: productName ?? this.productName,
      imagePath: imagePath ?? this.imagePath,
      originalPrice: originalPrice ?? this.originalPrice,
      availableStock: availableStock ?? this.availableStock,
      promoActive: promoActive ?? this.promoActive,
      promoType: promoType ?? this.promoType,
      promoLabel: promoLabel ?? this.promoLabel,
      discountPercent: discountPercent ?? this.discountPercent,
      buyQuantity: buyQuantity ?? this.buyQuantity,
      freeQuantity: freeQuantity ?? this.freeQuantity,
      quantity: quantity ?? this.quantity,
    );
  }
}
